language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-27
    - extra-google-m2repository
    - extra-android-m2repository

script:
  - cd src/android && ./gradlew build

branches:
  only:
  - master
  - dev

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify